spring:
    datasource:
        url: jdbc:postgresql://localhost:15432/postgres
        username: kiles
        password: 1234
        driverClassName: org.postgresql.Driver
    jpa:

        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
